# Generated by Django 3.1.3 on 2020-11-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20201115_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('drinks', 'drinks'), ('entrees', 'entrees'), ('treats', 'treats')], max_length=60),
        ),
    ]
