# Generated by Django 3.1.3 on 2021-02-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20210202_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('drinks', 'drinks'), ('entrees', 'entrees'), ('treats', 'treats')], max_length=60),
        ),
    ]
