# Generated by Django 3.1.3 on 2021-02-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20210202_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'drinks'), ('appetizers', 'appetizers'), ('treats', 'treats'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
